In [10]:
import numpy as np 
import pandas as pd

In [11]:
text='great product, i like it.'

In [12]:
import re
import string

In [13]:
with open('../Static/model/corpora/stopwords/english','r') as file:
    sw=file.read().splitlines()

In [14]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [29]:
def preprocesing(text):
    data=pd.DataFrame([text],columns=['tweet'])
    
    data["tweet"]=data["tweet"].apply(lambda x:" ".join(x.lower() for x in x.split()))
    data["tweet"] = data["tweet"].apply(lambda x: re.sub(r'http\S+|www\S+', ' ', x))
    data['tweet']=data["tweet"].apply(lambda x: re.sub(r"[^\w\s]"," ",x))
    data["tweet"]=data["tweet"].str.replace(r'\d+','',regex=True)
    data["tweet"]=data['tweet'].apply(lambda x: ' '.join(x for x in x.split() if x not in sw))
    data["tweet"]=data["tweet"].apply(lambda x: " ".join(ps.stem(x) for x in x.split()))
    return data["tweet"]

In [22]:
text

'great product, i like it.'

In [30]:
preprocessed_text=preprocesing(text)

In [31]:
preprocessed_text

0    great product like
Name: tweet, dtype: object

In [32]:
vocab=pd.read_csv('../static/model/vocabulary.txt', header=None)
token=vocab[0].tolist()

In [34]:
token

['test',
 'android',
 'app',
 'beauti',
 'cute',
 'health',
 'iger',
 'iphoneonli',
 'iphonesia',
 'iphon',
 'final',
 'case',
 'thank',
 'yay',
 'soni',
 'xperia',
 'love',
 'would',
 'go',
 'talk',
 'relax',
 'smartphon',
 'wifi',
 'connect',
 'know',
 'made',
 'way',
 'home',
 'amaz',
 'servic',
 'appl',
 'even',
 'question',
 'pay',
 'stupid',
 'support',
 'softwar',
 'updat',
 'fuck',
 'phone',
 'big',
 'time',
 'happi',
 'us',
 'instap',
 'instadaili',
 'xperiaz',
 'new',
 'type',
 'c',
 'charger',
 'cabl',
 'uk',
 'amazon',
 'year',
 'newyear',
 'start',
 'technolog',
 'samsunggalaxi',
 'iphonex',
 'pic',
 'twitter',
 'com',
 'shop',
 'listen',
 'music',
 'likeforlik',
 'photo',
 'fun',
 'selfi',
 'water',
 'camera',
 'picoftheday',
 'sun',
 'instagood',
 'boy',
 'outdoor',
 'hey',
 'make',
 'ipod',
 'dont',
 'color',
 'inch',
 'crash',
 'everi',
 'need',
 'realli',
 'drop',
 'ball',
 'design',
 'give',
 'anoth',
 'crazi',
 'purchas',
 'lol',
 'work',
 'hard',
 'play',
 'ipad',


In [35]:
def vectorization(ds,vocabulary):
    vectorized_list=[]
    for sentence in ds:
        sent_list=np.zeros(len(vocabulary))
        
        for i in range(len(vocabulary)):
            if vocabulary[i] in sentence.split():
                sent_list[i]=1

        vectorized_list.append(sent_list)
        
    return np.asarray(vectorized_list)
    

In [37]:
vectorized_txt=vectorization(preprocessed_text,token)

In [38]:
vectorized_txt

array([[0., 0., 0., ..., 0., 0., 0.]], shape=(1, 1157))

In [40]:
import pickle

In [45]:
with open('../Static/model/model.pickle','rb') as f:
    model=pickle.load(f)

In [47]:
model.predict(vectorized_txt)

array([1])

In [49]:
txt1='bad product, I hate it'

processed=preprocesing(txt1)
vectorized = vectorization(processed,token)
model.predict(vectorized)


array([1])

In [50]:
def get_predition(vectorized_txt):
    predcition=model.predcit(vectorized_txt)
    if prediction == 1:
        return "negative"
    else:
        return "positive"